name: CI

on:
  push:
    branches: [master, github-actions]
  create:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Verify
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./mvnw -B clean verify -Dstyle.color=always -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Publish Nightly Update Site
        if: github.ref == 'refs/heads/github-actions'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.UPDATE_SITE_ACCESS_TOKEN }}
          external_repository: jGleitz/test-update-site
          destination_dir: nightly/framework
          publish_dir: releng/tools.vitruv.updatesite.aggregated/target/final
      - name: Determine Release Version
        if: startsWith(github.ref, 'refs/tags/releases/')
        id: releaseVersion
        uses: olegtarasov/get-tag@v2
        with:
           tagRegex: releases/(.*)
      - name: Publish Release Update Site ${{ steps.releaseVersion.outputs.tag }}
        if: startsWith(github.ref, 'refs/tags/releases/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.UPDATE_SITE_ACCESS_TOKEN }}
          external_repository: jGleitz/test-update-site
          destination_dir: release/framework/${{ steps.releaseVersion.outputs.tag }}
          publish_dir: releng/tools.vitruv.updatesite.aggregated/target/final
          
